const messages = [
  "hey everyone! Introducing sophia and alana. I worked with Alana at magic!\nSkcd and mohit are good friends and they are currently leading the koding efforts at xAI!",
  "sophia pls watch out, this place is not safe",
  "@sophia semon wants to understand your business",
  "this is your shot sophia",
  "all of sophia\u2019s other friends survive",
  "Hi Sophia this is Jacob",
  "sophia what are you doing",
  "hey sophia! long time no talk, how have u been?",
  "he did this with sophia",
  "Hey Sophia!\nSending random file from the archive",
  "sophia and i are lacking in time to make this meetup continue happening. if you\u2019d be interested in taking it over please DM me :)",
  "this is a sophia website fact",
  "That\u2019s you Sophia",
  "Thanks to @sophia for organizing the dinner!",
  "reminded me of sophia strongly",
  "last night was a pretty Horny Sophia Night, huh",
  "Wow I ran into Sophia way sooner than expected",
  "and sophia sister",
  "Hey Sophia! A friend and I are going to optimize a kernel as an exercise/practical application of GPU knowledge. Matmuls are a classic, but do you have other pointers to interesting kernels to write or operations to fuse?",
  "Hey Sophia, great seeing you in person. I\u2019ll reach out to you if there is any data we need and if there is anything you have you think we would be interested in lmk",
  "This reminds me of how Sophia",
  "theres a line at the hagia sophia HMMM",
  "Hi Sophia, thank you for inviting me to this group",
  "Stewart has accepted the invite here. Please invite him to GPU perf @sophia !",
  "Ping! Sophia!",
  "sophia you try",
  "can't Sophia just book",
  "Sophia I have headphones for you",
  "sophia type sentence",
  "What else is the right cleaving descriptor that eg would explain Sophia being into metallurgy",
  "@sophia nevermind I'm just ordering here",
  "difference between sophia and me",
  "it was rly good to see Sophia",
  "Sophia lettuce hang out IRL",
  "sophia cleverly noticed a certain pattern in the triton results",
  "Previous Sophia said \u201ceverything is open source if you try hard enough\u201d lol",
  "new sophia bag",
  "But now Sophia is awakening",
  "hey Sophia, connecting you with Haowen here. He's looking into the data.",
  "sophia when did you sleep/wake today",
  "hey Sophia are you in SF? We should get coffee sometime \ni'm there 2-3 days a week\ni talked w Eric a while back when he was working on the model architecture",
  "Sophia want to hate Tess\u2019s tv?",
  "sophia this could be us in japan",
  "basically just teamlabs (sophia will definitely love u get to take off your shoes and splash around in water) and ghibli museum",
  "you can compete to have the best rendition of Sophia",
  "only sophia knows what it is",
  "i love sophia facts",
  "We're getting Sophia prescription glasses rn",
  "hi sophia i\u2019m in new york",
  "5:15 eta @sophia",
  "sophia have you run the evals",
  "@sophia can you bring me another donut",
  "Sophia are you with Sinclair right now?",
  "> be sophia\n> go to shanghai\n> get shanghaied",
  "Sophia: I actually hate any human art and music outside of gospel songs",
  "How has Sophia been emotionally?",
  "Sophia I'm thinking about the time you got in a revolving door segment with someone else (I think it was Master?) and immediately said \"I'm so fucking stupid I'm an idiot\"",
  "SOPHIA!",
  "is this the only time sophia has ever worn a hair tie",
  "Alright. Can I get Sophia, Stedman, and Panda to agree to Chatham House rules?",
  "going to make a version of this for sophia",
  "hi sophia!! this is ayush from mox. my time at the andromeda cluster is winding down and I\u2019d love to take you up on working together on data stuff!!",
  "please add to sophia images",
  "sophia 'terrorizer of asians\" wisdom",
  "Sophia when back",
  "Sophia just got in the shower",
  "happy thanksgiving sophia",
  "CAROLING SOPHIA",
  "last night Rachel and I were talking about you and I was like \u201chave you ever noticed that Sophia looks exactly like a Pre-Raphaelite painting?\u201d and Rachel was like \u201cyes she gets that a lot\u201d",
  "He now litigates everything I say about trans people eg \u201cthere are a lot of Sophia\u2019s\u201d",
  "Sophia is selling some sort of secret dataset she won\u2019t tell me anything about but apparently people really want. Maybe you guys might find it useful maybe not but figured I\u2019d make a group",
  "sophia wisdom influencer ark",
  "Sophia what the fuck",
  "@sophia I'm about to learn the secret sauce lmfao",
  "Maybe you can take Sophia\u2019s ticket if she wants to sleep in (?)",
  "sophia for the last 12 days",
  "That'd be great Sophia but I'm sure you're aware that I don't actually know anything and I rely on people who are at conferences or Twitter to teach me everything",
  "hi Sophia! this is Diana!",
  "thank you sophia!! <3",
  "your name? silly sophia",
  "I want to put this on my Sophia-style life moodboard",
  "hi sophia!",
  "i did see some places perfect for lil sophias",
  "yes but sophia sent message at the awkward time when \u201ctomorrow\u201d is ambiguous",
  "how is Sophia doing right now, by the way?",
  "merry christmas sophia!",
  "good luck sophia; we\u2019ve enjoyed knowing you",
  "this just seems like such a sophia-coded thing to say",
  "Getting Sam, and persian Sophia, banned today",
  "Sophia do you want to banya or are you too busy contemplating copper",
  "sophia jek and i meet at jeks at 5!",
  // "sophia",
  "Sophia I am planning a hike for Jenn\u2019s birthday next weekend, do you want to join?",
  "little sophia",
  "Sophia what do you think",
  "sophia gay ??",
  "Sophia is confused too",
  "@sophia we missed you :P",
  "this is hilarious sophia the guy alana & i might go to interview like recommended restaurants",
  "sophia can u book the third option",
  "My new nickname for Sophia is the \u201csmeckler\u201d",
  "@sophia this was me yesterday",
  "one of the most sophia tweets ive ever seen",
  "hey sophia, we tried accessing the data, it seems like a private bucket?",
  "the sophia neuron!",
  "i'm highbrow and elite sophia",
  "Very Sophia like place",
  "@sophia was the wanted poster definitely not you?",
  "sophia what is the best steamed pork bun in san francisco",
  "Sophia why are you awake at 4:30 am",
  "strawberry sultan Sophia",
  "@sophia",
  "Sophia, meet Daniel Eth! He works at https://theaipn.org/ developing relationships with members of congress around AI safety. We messaged earlier about how this is one of the most effective donation opportunities in AI safety.",
  "hello sophia",
  "me when sophia won't go to Woodhouse Fish Co.",
  "odsijfoidsjfoidjsoifjsoifj sophiaaaaa",
  "i feel like sophias pretty common too",
  "@sophia eta?",
  "Good work sweet Sophia",
  "Slack and discord have it. Appeal to the community about sam and Sophia sleeping in the space",
  "i like the idea of getting like spun around on the sophia great circle space elevator tether",
  "it is kinda crazy how sophia-core the problems in this startup are\nlike so weird! it's like designed for u!",
  "just like from sophias life",
  "but we get sophias jokes",
  "wait so sophia parent era?",
  "how are you sophia",
  "Whatever, not important, your answer is the good one Sophia is actually looking for \u2014 I'm just answering \"how feasible is brute force, if you happen to want that\" with \"quite feasible\".",
  "which imo is the ideal sophia work",
  "Sophia Wisdom",
  "Omg sophia\u2019s regina george arc",
  "sophia national security asset??",
  "I looked into it with Sophia a while ago. They chose not to expose it in ptx, even though you can see the SASS for it on the binary utilities webpage (but unfortunately that is not useful on its own). You can email me if you have a legitimate usecase, and I can forward it to the right person.",
  "sophia, you explain me this now. yes",
  "POST my experience with \"sophia wisdom\" is working as a wage-laborer and having her send me things she is \"thinking\" of (bourgeois). in this way we can see that this \"sophia\" figure is reactionary",
  "or is sophia just being idiot",
  "everyone knows neppy groomed you and you groomed sophia",
  "waiting for sophia CONFIRM",
  "very sorry sophia",
  "cc @sophia",
  "Sophia, does Monday work for you?",
  "also it must have been sophia",
  "Totally unrelated question, but are you familiar with a musician called Sophia",
  "i'm a very romantic person sophia",
  "Hey Sophia this is Evelyn, Birdie's sister. Are you free to come to a rat meetup to make pizza tonight?",
  "@sophia",
  "i think sophia and i already have a place?",
  "hello sophia\u2019s sister",
  "I\u2019ve been saying this about Sophia\u2019s siblings",
  "its a sophia wisdom classic",
  "Circus sophia!",
  "who\u2019s the bad guy sophia",
  "this tweet is for sophia btw :)\nhttps://x.com/__venki__/status/1981377221563420924\n\nand also kinda about jake",
  "Lol Typed and Sophia\u2019s location has not been updated since yesterday",
  "sophia give rock id",
  "happy birthday sophia!",
  "sophia has been out of silicon valley for too long",
  "Sophia i forgot your hat",
  "sophia!!!",
  "Philo Sophia",
  "Hey Sophia, nice to meet you!",
  "Sophia was able to escape",
  "recs:\n- Sultanahmet Meydan\u0131 for the obelisk\n- Hagia Sophia\n- Topkap\u0131 Saray\u0131 M\u00fczesi",
  "totalling my sophia against a lamppost",
  "who is this sophia?!",
  "noahide Sophia arc???",
  "i regret to inform you that i am no longer excited about the overnight ferry, and have recommended typed and sophia (who want to kyoto) fly directly to kyoto",
  "I think me, @sophia @Jennifer @Rachel Shu are all in mox so we can go together?",
  "Ur croissant is in the Sophia room",
  "we can do this little sophia",
  "me and sophia and ilana and thea will hang out without you",
  "@sophia there\u2019s a fun religious group at 16th mission",
  "\"did you know\", says Sophia, \"that in fact they'll let you get infinite phalloplasties?\"",
  "typed and Sophia are having harder time because they are travelling for a longer stretch",
  "@sophia can i eat your onigiri",
  "adding sophia who i thought was in chongqing oops \ud83e\udd7a",
  "Sophia get the bica",
  "> Thanks to Sophia Wisdom, Vijay Thakkar, Philippe Tillet, Dylan Patel, and Natalia Gimelshein who have helped me understand this phenomenon.",
  "Sophia\u2019s course is great",
  "hello sophia",
  "But Sophia said Sunday",
  "Sophia is this what my hair needs to look like for you to appreciate it",
  "sophia you should also meet lola woetzel https://x.com/glnoronha/status/1794022590077341910?s=46&t=zyG2L9f9xNbaYH_lgEZhRQ",
  "you will have to do planning with sophia",
  "sophia.jpg",
  "sophia when i retire can we be each others boss",
  "hey guys, I am under the impression that the deal went through. @sophia where can I find the data?",
  "theres the yushukan museum, sophia will love",
  "Sophia!!",
  "sophia we worked underneath the palo alto west elm",
  "@sophia you\u2019re famous https://www.astralcodexten.com/p/mantic-monday-12423",
  "hi sophia",
  "aspen do you have the keyboard or is it still sophia",
  "sophia please never change",
  "(this is how i plan to redecorate sophia's nest)",
  "New Sophia screenshots, what a pleasure",
  "Soumith this is Sophia she\u2019s a big GPU performance nerd. Creates cutlass Discords and stuff",
  "though typed is more JAP and sophia is more frum",
  "lmao it\u2019s really funny seeing a  roon tweet and being like \u201chuh did Sophia get to him\u201d and he\u2019s credited you in the next tweet",
  "stay away from me sophia",
  "@sophia You're going to have to evaluate a *lot* of silly ambiguous answers in your prediction market. Like, \"Sam got LK-99 poisoning\" will be easy, but like, a lot of them are very subjective.",
  "@sophia what\u2019s plan with Ada",
  "when I was on hella K with Calvin (most of my Calvin stories start like this) he was like \u201cwhy are you not dating Sophia\u201d and I had to think about it for [I have no idea how long, I was on K, I barely knew where I was] before saying \u201cmostly because I\u2019m a fuckup in general tbh\u201d",
  "Hello Sophia!",
  "me helping sophia fix her room",
  "sophia seven hours ahead of karpathy",
  "sophia help",
  "sophias got the zoomies!!!",
  "okay booking jungsik for @sophia @jek @cora and me at 5:30, April 29th. We can go to Coex mall + aquarium and explore gangnam before that!! It's 200pp \n- if anyone else wants to come, just hmu\n- if you cancel with < 3 days notice, or arrive > 30 minutes late you will be charged",
  "Sophia WILL become a in-context learning believer",
  "this is Sophia boob chat?",
  "that's so sophia omg",
  "wait sophia did u ever sniff",
  "sophia motivate me to go to richards pls",
  // "sophia",
  "Sophia was going crazy in airport security",
  "sophia met dave!!",
  "Sophia and i scare James",
  "@sophia actually it's you who has the coordination problem",
  "I wonder what black or chinese sophia would look like",
  "hallow sophia",
  "yeah sophia gets a key",
  "nope it's been Sophia the whole time ",
  "A lover of sophia",
  "typed \"i should be in the group chat i yearn way more than sophia\"",
  "trying to get boobs that look worse than sophia's",
  "also hi sophia! we\u2019re mutuals on twitter, my account is @simulatedsnow",
  "sophia might need a breast reduction",
  "@sophia does AI stuff and has a contract with a lab or something to do app modeling",
  "what the fuck sophia",
  "@jek @sophia lazy bear 245",
  "hihi sophia! i've really liked the people i met at wrestling and my grouphouse is looking to fill a room, so can i post in monke about it and/or do you know of other channels that would filter for a similar demographic? :]",
  "woah @sophia is pink onion without us",
  "hm yeah so maybe we say the sophia standard of living costs like $50k annually?",
  "happy birthday sophia",
  "@sophia you can put batch*d_model fp8 activations in SRAM and then do a transformer MLP as a loop over d_ff (streaming both weights through) that accumulates an output of size batch*d_model in fp32, right??",
  "not a problem when sophiacorp is a billion dollar company",
  "idk about the divinity stuff but it was funny to see \"Sophia, Wisdom\".",
  "it's a secret sophia",
  "why did you birth the demiurge Sophia :(",
  "Sophia maybe you should join",
  "Wait so what is Sophia's new job about?",
  "https://lu.ma/hvr3ibuu\nYoyooo Sophia would love to see ya at my bday hang!",
  "happy new year sophia",
  "i'm glad you aren't angry anymore sophia",
  "sophia in slack they refer to your dataset as SophiaWisdom",
  "I just remember being at Noisebridge and there were a bunch of people talking, and I was like \"Okay, of course Sophia is the best person at this table, and we should get each other's numbers.\".",
  "i was telling sophia about it",
  "anyways I'd love to talk about this some time as i just am having fun with the competiton, thanks @sophia",
  "I was gonna say I thought Sophia was like 12",
  "we should go to house of prime rib when sophia is back",
  "sophia is seeing a woman all dolled up",
  "this room is very sophia coded",
  "sophia find me a man or a tran",
  "Common Sophia experience",
  "sophia's sister",
  "sophia will literally take pictures of her fondling her boobs with my phone",
  "@sophia you have a lot to learn",
  "alt sophia vibe",
  "Sophia picked my hotel",
  "@sophia https://sfstandard.com/2024/08/29/rickhouse-reddit-tipping-you-you-xue-lawsuits/",
  "@sophia lemme know if u go i have your uzbekistan wisdom hat",
  "tfw the lucy culture steppe pastoralists get conquered by agriculturalists from the sophia culture and get longhoused",
  "Sophia: \"what's it called when you bang your cups together? Cheers? Toasting?\"",
  "i am coveting my neighbours wife sophia",
  "happy to call rn if you're available @sophia",
  "what are u talking about sophia",
  "@sophia what are you training a model for?",
  "in case anyone is wondering what's going on @sophia has control of @bird's twitter ",
  "yeah there is only one marfan's expert in sophia's life",
  "I think sophia comes across as more comfortable than you",
  "Sophia it sounds like the answer to your question is you should interview at Nvidia!",
  "Sophia coded. ",
  "sophia: that's awesome",
  "Sophia just took insane amphetamines and wrote 82B tokens of good code, and is hiding it.",
  "Sophia hates triton",
  "sophia does NOT like being told she has conditions",
  "introducing the workplace to sophia terminology",
  "Good old pugilistic Sophia.",
  "\u201cwow sophia got me off the waitlist what a baller\u201d but no, it\u2019s getmagic.com not magic.dev",
  "30 dollar deposit so @sophia it's up to you",
  "@sophia do you have bitcoin",
  "worse case i take a small loan from the bank of sophia",
  "I'm asking someone to explain at a mechanistic \"gears\" level in the way Sophia tried to just now. Or link to a suitable resource.",
  "@jek @sophia @Kevin Kwok r u guys up yet",
  "hey sophia",
  "they have a sophia",
  "eep well, sweet sophia",
  "sophia nazi??",
  "@sophia could we try this again with 24-48 hours notice :)))",
  "it is sophia ",
  "sophia activate the shock collar",
  "wait sophia ru in japan still? i thought u went to chongqing but maybe i am confusion lol",
  "Sophia are you on catchMe",
  "oh Sophia",
  "Based sophia moment",
  "hey Sophia you ever put anything cool into your dataset",
  "Griffin <> Sophia",
  "Not-alive Sophia designed it. CPU stuff but the vibe of the textbooks feels similar to the lack of abstractions/direction/ consistency of Nvidia docs",
  "i hope you\u2019re having a nice birthday time sophia <3",
  "Hi Sophia",
  "tweets from the sophia dimension",
  "@sophia youd like this site, proxibid",
  "when you realize that the anthropic analog of sophia is a gay furry who has sex in hotel rooms while her friends watch - it's no surpise who wins",
  "hi sophia!!!!!",
  "jek have you seen me listening on my studio monitors as sophia and kipply rap",
  "happy birthday sophia",
  "also is @sophia alive",
  "DEALS MINDSET SOPHIA",
  "happy birthday sophia <3",
  "sophia is likely asleep though",
  "we are writing so much code for you to convert into CUDA sophia",
  "I showed my id to someone at a party and she immediately said \"you must know Sophia\"",
  "Sophia are you hanging out with henry???",
  "\u201c\u201c\u201cgerman unification was the worst thing in human history\u201d - joseph stalin\u201d -  henry morgenthau\u201d - sophia wisdom",
  "sophia you're likely asleep",
  "Really though? After the board already approved the Microsoft investment which had a huge portion of profits going to Microsoft directly? I agree w/ Sophia, this is hard to believe.",
  "the SophiaWisdom dataset",
  "come home sophia \ud83d\ude2d",
  "when does sophia uh",
  "https://partiful.com/e/JILuqprVX6uvIuZ1DRwv\n\nSpecial Edition: Changing of the Guard!\nThis Sunday will be the final Wrestling in the Park organized by Keri/Sophia - our dear friend Bol\u00e9 will be taking it from here. Bol\u00e9 knows how to struggle and how to have a good time. See you all soon <3",
  "@sophia what address do u want",
  "o hi sophia",
  "@cora @sophia did u two get on a train",
  "SOPHIA THIS IS FOR U",
  "my strong recommendation is that they need to clean the shit out of sophia face",
  "With sweet Sophia?",
  "sophia content",
  "To be clear, this is literally something I learned of from Sophia. I'm really surprised I had never heard of German coal butter before, but she answered one of my childhood confusions.",
  "sophia would be a good trader",
  "happy new year sophia!",
  "Sophia are you ok?",
  "@sophia https://x.com/astridwilde1/status/1828253583361630555?s=46&t=zyG2L9f9xNbaYH_lgEZhRQ",
  "i want Sophia reading links",
  "It took Sophia and I like",
  "sophia wanna come with me and ilana",
  "sophia alive!!",
  "no idea what this is sophia haha",
  "sophia can you cofounder match me",
  "we have a rone for u to give to casey sophia",
  "Idk what typed and Sophia talking about",
  "It\u2019s very sophia coded and I\u2019m here for it",
  "sophia is getting dinner with him",
  "lmfao okay yes \"sophia\" is probably an easier one",
  "thanks sophia i knew i could count on you",
  "careers@sophia",
  "honestly when sophia and i weren't talking",
  "however, sophia is more difficult",
  "cc @sophia",
  "Sophia?",
  "other sophias have went",
  "front desk at my hotel says next day after 2pm for luggage delivery to kyoto hotel fyi @cora @sophia",
  "> It\u2019s going to be a challenging market to resolve as many user-submitted answers aren\u2019t well-defined and overlap with other answers. The creator Sophia will need to be discerning when deciding when an appropriate time to resolve is.",
  "Pls explain Sophia",
  "sophia was ignoring me",
  "I would never take joy in the misery of my friends sophia",
  "why is this so sophia-coded",
  "Thankssss Sophiaaaaa",
  "sophia wins again",
  "also sophia i really miss you and we should hang out soon. really want to know how you\u2019re doing",
  "u and sophia balance out",
  "she probably liked sophia more then",
  "Sophia can\u2019t handle it",
  "@sophia for context its not like \"im swamped can we reschedule\" but making me wait for over an hour and making excuses about sergey brin",
  "sophia let's do it",
  "@sophia I would like to invite him FYI. He worked with Scott back in the good old nervana days. And is 10 times smarter than me. I am just a potato.",
  "I want to pull a Sophia Wisdom, as they say.",
  "it's such a sophia thing to have happen",
  "makes me sad sophia's gf has been beating her",
  "Sophia what does this mean",
  "yes sophia wisdom is now the richest girl in the world",
  "Ah Sophia\u2019s suggestion was 6pm",
  "Sophia: *Scooby Doo noise*",
  "i just vemoed sophia",
  "I am interested in Sophia and Azlen\u2019s takes",
  "wait for sophia to wake up",
  "after sophia and i are done being AWESOME",
  "sophia do you want this uzbeki hat",
  "Sophia u didn\u2019t clean up any of your holy oil stuff >:(",
  "hey sophia hows magic going",
  "@sophia you should go to this in march https://www.instagram.com/reel/DF6DwhjSKR8/?igsh=NTc4MTIwNjQ2YQ==",
  "sophia can probably demonstrate",
  "@sophia eta?",
  "Yoooo sophia why not coming",
  "tiny spoiler for big sophia",
  "great timing @sophia https://www.pekingnology.com/p/china-now-asking-all-hotels-to-accept",
  "@sophia do you remember bo",
  "sophia i smoked a cigarette inside my room and got a headache ;;",
  "hai sophia",
  "would be sweet if we could practice shooting on sophia's property",
  "happy \u201824 sophia",
  "sophia pls",
  "wait sophia",
  "sophiawisdom@gmail.com ?",
  "sophia \"never listens to spotify links\" wisdom sending a link?",
  "oh aspen showed us your website, incredibly sophiacore",
  "i recall sophia posted her face back in the anthropic trial days",
  "Frustrating Sophia never applied for survivor",
  "Sophia has met her",
  "Happy Sophia Day !",
  "i want sophia to argue with him",
  "hii sophia",
  "sophia doesn't like my bag",
  "Hi sophia, it's Tao!",
  "holy shit sophia",
  "i also like the poster house but thats more a sophia kipply activity",
  "@Slim @sophia dumppp",
  "less allergens for sophia :))))",
  "anyone else? @sophia",
  "sophia uuisdom",
  "lets go shopping here for sophia's new look",
  "it's kinda what you wantt odo to future sophia",
  "Wait Sophia you\u2019re oct 7 too? :0",
  "hai sophia",
  "sophia i think my company is a madhouse help",
  "lots of clascci characters sophia",
  "bi sophia",
  "sophia intellectual property (sip)",
  "Hey Sophia do you want to go to Archimedes Banya next weekend?",
  "i cal her \"sophia the weak\"",
  "also i have someone pants?? lmao. sophia has a picture. they\u2019re gray and large",
  "sophia\u2019s reverend mother arc when",
  "ok tiny bit for sophia",
  "Cc @sophia",
  "i claimed 4 tickets to teamlabs planets on may 9th 8pm, three people are free to claim (for those who have been before ,its now 1.5x bigger and has new stuff). i reserve one for @sophia because i think she will LOVE IT",
  "hey! wanted to make a group to introduce you. tal worked on penumbra and did a bunch of (web)gpu client side proving work and set some speed records, sophia has done a bunch of gpu programming for ML. tal is in town until the end of the week and maybe you would enjoy chatting",
  "Thank you sophia you are amazing",
  "this is sophia coded",
  "SOPHIA NEGATIVIA",
  "will you be a GUY on ChatGUY.com if i make it sophia",
  "internally we call sophia\u2019s dataset \u201csophia wisdom\u201d so there are constantly slack posts like \u201cwe need to understand what\u2019s happening to sophia wisdom\u201d and \u201cwhy does this spreadsheet have two sophia wisdoms\u201d and \u201ci think this explains sophia wisdom\u201d",
  "sophia junior",
  "@ slim and sophia: when do each of you plan to get back to the c&c?",
  "Hey Sophia what is up?",
  "@sophia have you done a consult",
  "sophia help",
  "anyways, i like this new sophia vibe",
  "no I think sophia of all people might understand objective C",
  "u should pay sophia for first dibs on her younglings",
  "young sophia",
  "good sophia clothes?",
  "@sophia where should i get you?",
  "@sophia wyd in montreal?",
  "\"i'm just like hitler\"\n- token saleswoman sophia wisdom\nis THIS the woman you want selling you tokens?",
  "ok sophia",
  "sophia do u know her",
  "Hey Sophia, how ya doing? Haven\u2019t seen you in a while",
  "what's the smallest $X over 4 years sophia would work at meta for",
  "@sophia @Chris Beiser @jek",
  "I told him he fucked over me, sam, dan, jeremy, sophia, and our contractors and I\u2019m not interested in wasting more time on him",
  "But yeah, they're pretty much doing Sophia's idea directly. They're just directly doing CO2 capture, then chemistry, and getting edible fats out.",
  "lot of people like sophia's boobs",
  "sophia do you want an intro to my friend alex in new york",
  "hi sophia",
  "@sophia according to my colleague, you don't want to fuse top k into the epilogue of a gemm. You want an efficient top k. Look for \"efficientNMSPlugin\" in the tensorrrt GitHub repo. It's not top k, but the concepts used inside of it are similar to how you implement top k fast.",
  "@sophia phone number",
  "i still think it was really fun how you gravitated to my mom and sophia gravitated to my dad",
  "Sophia you did",
  "maybe taller than naia though i don\u2019t really remember if naia is taller than sophia",
  "Ren to sophia",
  "Sophia, we're on our way, we'll be at dogpatch boulders at 3:25",
  "sophia-ass statement",
  "attributable entirely to the sophia tokens im sure",
  "i will come visit sophia instead",
  "Sophia I'll pay you $20 a month if you send me 20 memes a month",
  "sophia getting up",
  "I'm so glad Sophia is here now guys ",
  "sophia didn't you used to be a big skiier?",
  "Wait is Sophia just a treasure hunter",
  "Sophia rn fr",
  "@sophia can i inject you with this??",
  "@korea @cora @Dylan Patel @sophia @jek \nWe should make a Jungsik reservation in the next few days, can I get approval voting for; \n- april 28th 6PM\n- 29th 5:30PM or 12PM\n- 30th 5:30PM or 12PM",
  "tweets from the sophia dimension",
  "@sophia @Slim?",
  "noooooooo sophia that's how you spread the prion disease \ud83d\ude2d\ud83d\ude2d\ud83d\ude2d",
  "where is Sophia now?",
  "fr sophia learns to drive in a porsche when",
  "hey sophia",
  "Sophia\u2019s Sexy Chess Index",
  "how are you sophia",
  "alt sophia energy",
  "i think sophia is more jewish than typed",
  "Shares in Sophia inc just up by 100%\n\nhttps://x.com/AdamEisgrau/status/1854667538799681937",
  "That makes sense, thanks! Hi, Alana; nice to meet you!\n\nI need to get some work done and I got a vaccine earlier that will probably leave me zonked for a couple days, but let me write up what I'm thinking in a bit, although you probably have a good idea already from having talked to Sophia",
  "and sophia wanted to see it",
  "sophia reading about christian monks in the 13th centry: i'll never understand people who care about astronomy",
  "@sophia do you know of anything going on tonight",
  "\"neo-sophia\"",
  "Hey Sophia, I\u2019m getting ready to drive over in a few minutes to take us to the hike",
  "As i walked to Sophia",
  "How i feel when Sophia sends voice memos here",
  "Thank you for the pity laugh Sophia",
  "hi sophia",
  "I\u2019m working hard so Sophia can work hard when she returns from red China",
  "i sent it to sophia but not to neppy of course",
  "i'm not trying to beat sophia here lol",
  "its so over when sophia wisdom 2 drops",
  "I think Tyler cowens infovore is the best rn? I think it feels very accurate of a category to call Sophia an infovore?",
  "Sophia! I launched a thing! Can I show you it? I\u2019d love to get your initial feels and thoughts abt it",
  "i think hes coming back tn sophia come diagnose",
  "do you wanna come to daeho @cora @sophia",
  "Sophia I need you to revive me from drowning ",
  "hey Sophia! henry mentioned the class, seems super interesting",
  "god morning sophia",
  "what will you use to harvest people, sophia?",
  "@sophia thought you were referring to the CDNA2 white paper",
  "sophia stays winning",
  "i wanna buy sophia insurance!!!",
  "everything coming up sophia",
  "Yay Sophia is back",
  "actually maybe i go with typed and sophia this afternoon idk",
  "hi! Sophia <> Tony re 60B tokens",
  "R u going to do it Sophia?",
  "hey sophia! i\u2019m a friend of lucy \u2014 she mentioned you and said i should say hi! i\u2019m passing through SF until monday evening. would love to meet up!",
  "omg sophia that is insane",
  "Sophia i have haircut in august wanna come",
  "Hey sophia",
  "Hello Sophia",
  "who is Sophia",
  "that's me traveling with sophia",
  "It pays to be a winner sophia",
  "sophia are you coming",
  "Sophia has a very interesting dataset that she'd like to sell to us.",
  "Imagine being Sophia and not going here",
  "10: sophia eric oliver tristan jek tri clive prasun daniel david",
  "@Sam Svenningsen  @Kognise @sophia @t11s y\u2019all are coming from SF so consider carolpooling maybe",
  "Hi Sophia, I really need you to come to work today and the rest of the next 2 weeks. I have no way to justify this to our Vienna team, who are currently visiting.",
  "sophia would never",
  "he described sophia as all his strengths and weaknesses amplified",
  "@Kognise @sophia I don\u2019t know where in sf you guys are",
  "Hi Sophia",
  "sophia replace with her",
  "oh my god sophia",
  "sophia is negging me",
  "sophia get out of there!!!",
  "kipply sophia and i are discussing why i don't pass",
  "{home: \u201csan francisco\u201d, \u201cfriends\u201d: [\u201csophia\u201d, \u201cping\u201d, \u201ctess\u201d, \u201cespes\u201d]}",
  "means your retirement project will be a novel and sophia\u2019s will be a substack",
  "Was going to send to Sophia but she had already replied lol",
  "https://arxiv.org/abs/2312.08595 @sophia new version of your favorite analysis",
  "sophia fujoshi arc??",
  "Lol, emeline sent me this, saying: not even Sophia\u2019s https://meetu.ps/c/574rB/gfrlH/a",
  "food for sophias",
  "'sophia's not a racist'",
  "i want to see survivor sophia",
  "Did you pick the last name Wisdom because Sophia means Wisdom",
  "sophia type tweet",
  "anyways i need to go to sleep but see you soon hopefully sophia",
  "@sophia",
  "Hi Sophia",
  "@sophia also you if you want",
  "sophia's 3b1b",
  "i was talking about how if i was breaking up in ltr on this trip i would most want to hang out with sophia",
  "ttyl sophia :)",
  "Kyoto: Hotel Minn is great and cheap when u use booking.com @cora @sophia https://maps.app.goo.gl/PtAM9Ya95UthQrMYA?g_st=com.google.maps.preview.copy",
  "sophia WWWWWWW",
  "i picture this as the kind of thing that 70yo sophia would say",
  "okay - gonna look to book this in the next couple days! \nseems like it's {panda, me, sophia} confirmed going, lmk if ur interested.\n\nas a reminder, deets here: https://partiful.com/e/eZjDjRnXy9Ax3RL1VayQ\nThu May 22 -> Mon May 26 & we'll be in Ensanada on Saturday",
  "Sophia, do you have an email?",
  "sophia mentioned in matxchat",
  "sophia the slinker upper",
  "sophia racist ???",
  // "Sophia",
  "should I be able to read my own replies to the \u201cSophia post\u201d?",
  "Sophia and I are on en route",
  "roommates + Sophia + sophia",
  "sophia knows how it isn't",
  "What is Sophia up to lately?",
  "sophia would send them my way for free",
  "how are you sophia",
  "No sophia today?",
  "Thanks, Tao! \n\nSophia, it's great to connect! It would be great to learn more about your interests in policy and political giving and ways ARI might be a good fit. Do you have time to chat sometime in the next week?",
  "sophia wants me to come to his party",
  "pov: sophia is looking at you between your implants",
  "will walk in max and sophia\u2019s direction",
  "yes sophia",
  "oh sophia remind me to ask u about ur extremely specific emotion posters",
  "sweet sophia \ud83d\ude14",
  "@sophia watching another HBO doc",
  "hey sophia. adam paszke would be a cool person to add to the gpu perf thread. he's been working (among many things like dex, jax, first author in pytorch) on his own triton-like dsl that beats everything else, he said he'll release it soon.",
  "And Sophia was enlightened",
  "pixarified sophia",
  "sophiawisdom@gmail.com ?",
  "PREP SOPHIA FOR SURGERY",
  "we were on hella K and talking about our love lives and he was like \u201cwhy don\u2019t you just date Sophia? She\u2019s very smart\u2026 and interesting\u2026 and CONFIDENT\u201d and I was like \u201cman it sounds like You should be dating Sophia\u201d and he was like \u201chonestly\u2026 Yeah.\u201d",
  "Hey Sophia! This is Calvin. Here are the videos:",
  "its sophia",
  "@sophia @Max K where did you go?",
  "so no sleep for Sophia until she builds it!!",
  "Yooo Sophia, just saw this",
  "\"Sophia you gotta stop sending me traditional Tunisian musicians\"",
  "thank you sophia. ning?",
  "that's because sophia",
  "oh I put on a song for ctat and Rachel and they were like \u201cSophia will love this\u201d. It\u2019s by Exuma, who made Satanic calypso music",
  "i hope you\u2019ve been doing well sophia",
  "hey sophia, sorry for the wait. we've been quite busy on our end recently so havent got time to look into the data too deeply. but I will try to get back to you by EoW.",
  "sophia!",
  "sophia convince typed to come banya",
  "yay ive made a reservation for 8 people 5:30 april 30th! @jek @Dylan Patel @cora @sophia",
  "There we fucking go, thank you Sophia",
  "likewise! im grateful for your friendship sophia. hope youre doing well",
  "Sophia is just hittting it out of the park today",
  "sophia is on the island",
  "Sophia do you want to hang out rn",
  "you could do this itd be a good sophia bit\nhttps://x.com/Buffalojilll/status/1981839651485987173",
  "waow its sophia",
  "Hey Sophia, good to reconnect!",
  "our hotel has a brochure with sophia on it",
  "@sophia could be fun https://docs.google.com/forms/d/e/1FAIpQLSe75okHe5c1yGEuPg_GTAi-fRuwuYbDQLghNJnO01i_GDhy4w/viewform",
  "this is @sophia bait",
  "hey sophia you have good taste",
  "\"it was distracting how fun she was to talk to\" -max re sophia",
  "Ok Sophia can you do me favor lol",
  "this is why sophia is so powerful",
  "Hi Sophia, I hope you had a good Christmas ",
  "me with sophia's boobs",
  "i like this voice sophia",
  "Sophia come to party!!!",
  "@sophia post voice",
  "upper class sophia time",
  "im like the cumtown guy but for sophia bits",
  "I am going to be hyper-competitive in this stupid class - other-Sophia is awesome that she made such a complex beginners class",
  "how have u been sophia",
  "sophia be like",
  "sophia type shit",
  "sophia has already achieved temporal success",
  "Sophia, meet McKenna Fitzgerald from https://ari.us/! As I mentioned earlier, ARI develops relationships with members of congress about AI policy and is one of the most cost effective ways to give to AI safety!",
  "i think we can eventually drag you some fraction of the way towards sophia\u2019s ~~body positivity~~",
  "tbh i was like \u201cmaybe sophia isn\u2019t going to have enough stuff to do, i should send her to a trading bootcamp\u201d",
  "hey Sophia I\u2019m still very depressed but we need you to settle a disagreement between us",
  "i guess sophia is giving class right now",
  "you know sophia i very much enjoy these types of conversations with you. last time we talked about something similar  i ended up watching a bunch of evangelical sermons and there was one by billy graham that i think captures the essence you\u2019re describing extremely well",
  "@sophia is a very good predictor, she is schooling everyone this season",
  "'urgent: sophia is in town'",
  "I love it. Always be reading. Thanks Sophia.",
  "sophia want to make a move?",
  "sophia Mining Stuff column when",
  "good work, Sophia, I guess",
  "Sophia ill walk to you?",
  "sophia help",
  "sophia @ abizer school of driving when",
  "me: cares about looking pretty\nsophia: no not like this!!!",
  "lol sophia you're consuming the most autistic nl content",
  "who wants to see mt fuji? trying to decide whether to do it otw kyoto -> tokyo with @sophia @cora or on the tokyo<->nagoya loop with @Azlen Elza @Selina",
  "@sophia 7pm banya",
  "The sophia store is open for business",
  "nini sophia",
  "sophia what do i do!!!",
  "Speaking of Triton, @sophia did you see that tl.reshape() now exists? I remember that you had a compelling usecase for this operation.",
  "Sophia day !!",
  "sophia how fast can you type",
  "Oh, I see, I see, \"the slowdowns are equivalent between Peter's example and Sophia's new example\".",
  "@sophia Is there an efficient built-in way to convert an int8 2:4 sparse matrix (in the tensor core format) into an fp16 2:4 sparse matrix? I don't think so. Right?",
  "Yo Sophia this is Ryan",
  "im gonna start telling ppl that's why we call you Sophia",
  "How is Sophia doing?",
  // "sophia",
  "wya sophiaa",
  "so weird Sophia I\u2019m so amused by the odds of high school guy doing this",
  "@Max K @sophia @cora approval",
  "sophia if the media takes the h1b immigrant gone bad story and keeps shoving it down our throats for the next n months im gonna be so sad",
  "This might be the most unhinged Sophia take yet, and that's saying something",
  "if we go ill bring u some bred sophia",
  "sophia is intersex",
  "i told sophia you were super into it!",
  "Hey Pablo, would like to connect you with Sophia here.",
  "maybe you can do a complete sophia make over by then",
  "sophia has perfect boobs so it put a unrealistic standard in my mind",
  "sophia your job is to catch us up",
  "sophia went to his thing",
  "is sophia gonna be okay?",
  "Sophia, can give access to the doc I requested just now?",
  "oh no... you're possessed now... Succubus Sophia!!!!",
  "sophia should i bring your hat",
  "@sophia remove",
  "sophia inbound to your location",
  // "sophia",
  "thank you grandmaster sophia",
  "looks like sophia",
  "sophia my mom thinks you should get ffs",
  "Hey Sophia. How are you doing? A friend of mine, Jose, is starting up in the infra/interconnects/fault tolerance space. He used to be at MSR earlier. Could you add him to the group? His no.  +1 203-676-9255",
  "sophia style",
  "i can introduce you sophia",
  "Sophia while I don't disagree with you in this instance, with all due respect you are not my bellwether for legality",
  "I love the Sophia nook",
  // "@sophia @Aaa need to hop on a call asap, Google basically gave us a one-time offer price and it\u2019s no where near where we were hoping for",
  "Thanks sophia",
  "how i feel when i see sophia",
  "sophia you could come over and we could cook things together! like cool and unusual things!",
  "@sophia input",
  "can call once you've synced w sophia",
  "sophia one year ago",
  "i\u2019m with sophia i think",
  "sophia is getting a very special gift james"
]
let allMessages = "";
let currentMessage;
let wipe = false;
let myInterval = 11; // 200


function chooseMessage() {
    currentMessage = messages[Math.floor(Math.random() * messages.length)].split(" ");
    let mayaIndex;
    let originalMaya;
    for (let i = 0; i < currentMessage.length; i++) {
        if (currentMessage[i].toLowerCase().includes("sophia")) {
            mayaIndex = i;
            originalMaya = currentMessage[i];
        }
    }

    let preMaya = currentMessage.slice(0, mayaIndex);
    let preMayaNumCharacters = preMaya.join(" ").length;
    let postMaya = currentMessage.slice(mayaIndex + 1, currentMessage.length);
    let postMayaNumCharacters = postMaya.join(" ").length;

    let message = {
        "preMaya": preMaya,
        "preMayaNumCharacters": preMayaNumCharacters,
        "postMaya": postMaya,
        "postMayaNumCharacters": postMayaNumCharacters,
        "originalMaya": originalMaya
    }
    return message;

}

let textSpans = [];

function createNewMessage() {
    let newMessage = chooseMessage();
    while (newMessage.preMayaNumCharacters >= 20 && newMessage.postMayaNumCharacters >= 30) {
        newMessage = chooseMessage();
    }

    const newDiv = document.createElement("div");
    newDiv.classList.add("current-message");

    if (newMessage.preMayaNumCharacters > newMessage.postMayaNumCharacters) {
        // Left is longer
        newDiv.style.alignItems = "flex-end";
    } else {
        newDiv.style.alignItems = "flex-start";
    }

    // LEFT
    const leftSpan = document.createElement("span");
    leftSpan.classList.add("flex-item");
    leftSpan.classList.add("left");
    leftSpan.innerText = newMessage.preMaya.join(" ");
    newDiv.appendChild(leftSpan);
    leftSpan.style.transform = "translateY(0px)";
    leftSpan.title = leftSpan.innerText;
    textSpans.push(leftSpan);

    // CENTER
    const centerSpan = document.createElement("span");
    centerSpan.classList.add("flex-item");
    centerSpan.classList.add("center");
    centerSpan.innerText = newMessage.originalMaya;
    newDiv.appendChild(centerSpan);
    const randomDuration = Math.floor(Math.random() * 9) + 2;
    centerSpan.style.animation = `fadeIn ${randomDuration}s infinite`;
    centerSpan.title = centerSpan.innerText;
    textSpans.push(centerSpan);
    // RIGHT
    const rightSpan = document.createElement("span");
    rightSpan.classList.add("flex-item");
    rightSpan.classList.add("right");
    rightSpan.innerText = newMessage.postMaya.join(" ");
    newDiv.appendChild(rightSpan);
    rightSpan.style.transform = "translateY(0px)";
    rightSpan.title = rightSpan.innerText;
    textSpans.push(rightSpan);
    document.getElementById("message-container").appendChild(newDiv); // ☆
    shuffle();
}

function ready() {
    createNewMessage();
    myInterval = Math.random() * 2222;
    setTimeout(ready, myInterval);
}

document.addEventListener("keypress", (e) => {
    // if (e.key == 'm' || e.key == 'a' || e.key == 'y') {
    //     createNewMessage();
    // }
    createNewMessage();
});

function shuffle() {
    for (let i = 0; i < textSpans.length; i++) {
        const y = textSpans[i].getBoundingClientRect().y;

        if(y < -50) {
            document.getElementById("message-container").removeChild(textSpans[i].parentElement);
            textSpans.splice(i, 1);
            i--;
            continue;
        }

        const orig = textSpans[i].title;

        const factor = (window.innerHeight - y) / window.innerHeight / 2 - 0.3;
        let newText = "";

        for(let j = 0; j < orig.length; j++) {
        const char = orig[j];
        if(Math.random() < factor) {
            newText += orig[Math.floor(Math.random() * orig.length)];
        } else {
            newText += char;
        }
        }

        textSpans[i].textContent = newText;
    }
}

ready();
